version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: "Running Maven Build"
          command: mvn clean install   
  deploy:
    docker:
      - image:circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "A Deploy Job"
 
    
