version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "A build Job"
  deploy:
    docker:
      - image:circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "A Deploy Job"
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
      - deploy
 
    
