version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/CirleCI
    steps:
      - checkout
      - run:
          name: "Running Maven Build"
          command: mvn clean install 
###################################################
  circleci-build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/CircleCI
    steps:
      - store_artifacts:
          path: ~/CircleCI/target/CircleCI-0.0.1-SNAPSHOT.jar	  
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "A Deploy Job"
 
    
